### ISSUE TITLE
npm package installation failing for `linux` os for `x64` arch

### ISSUE THREAD

**Issue by sc231997** [tailcallhq/tailcall#616]
### Prerequisites

- [x] I have checked the existing issues to ensure this is not a duplicate.
- [x] I am running the latest version of Tailcall.

### Describe the bug
npm package installation failing for linux - x64 platform.

### Steps to reproduce

Use the sandbox https://stackblitz.com/edit/tailcall-playground?file=index.js

### Expected behavior

Correct package should get install without any error.

### Actual behavior

Installation fails with the errors shown in below log.

### Environment information:

- **Operating System**: Linux
- **Tailcall npm Version**: 0.14.14

### Logs

```
Failed to install optional dependency: @tailcallhq/core-windows-i686-gnu npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @tailcallhq/core-windows-i686-gnu@0.14.14: wanted {"os":"windows-gnu","arch":"i686"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    windows-gnu
npm ERR! notsup Valid Arch:  i686
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-11-10T03_32_25_655Z-debug-0.log

Failed to install optional dependency: @tailcallhq/core-windows-x86_64-gnu npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @tailcallhq/core-windows-x86_64-gnu@0.14.14: wanted {"os":"windows-gnu","arch":"x86_64"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    windows-gnu
npm ERR! notsup Valid Arch:  x86_64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-11-10T03_32_25_813Z-debug-0.log

Failed to install optional dependency: @tailcallhq/core-windows-aarch64-msvc npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @tailcallhq/core-windows-aarch64-msvc@0.14.14: wanted {"os":"windows-msvc","arch":"aarch64"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    windows-msvc
npm ERR! notsup Valid Arch:  aarch64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-11-10T03_32_25_841Z-debug-0.log

Failed to install optional dependency: @tailcallhq/core-linux-aarch64-gnu npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @tailcallhq/core-linux-aarch64-gnu@0.14.14: wanted {"os":"linux-gnu","arch":"aarch64"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    linux-gnu
npm ERR! notsup Valid Arch:  aarch64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-11-10T03_32_25_462Z-debug-0.log

Failed to install optional dependency: @tailcallhq/core-linux-x86_64-musl npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @tailcallhq/core-linux-x86_64-musl@0.14.14: wanted {"os":"linux-musl","arch":"x86_64"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    linux-musl
npm ERR! notsup Valid Arch:  x86_64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-11-10T03_32_25_426Z-debug-0.log

Failed to install optional dependency: @tailcallhq/core-apple-arm64 npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @tailcallhq/core-apple-arm64@0.14.14: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  arm64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-11-10T03_32_25_492Z-debug-0.log

Failed to install optional dependency: @tailcallhq/core-linux-x86_64-gnu npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @tailcallhq/core-linux-x86_64-gnu@0.14.14: wanted {"os":"linux-gnu","arch":"x86_64"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    linux-gnu
npm ERR! notsup Valid Arch:  x86_64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-11-10T03_32_25_455Z-debug-0.log

Failed to install optional dependency: @tailcallhq/core-apple-x86_64 npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @tailcallhq/core-apple-x86_64@0.14.14: wanted {"os":"darwin","arch":"x86_64"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  x86_64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-11-10T03_32_25_425Z-debug-0.log

Failed to install optional dependency: @tailcallhq/core-windows-x86_64-msvc npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @tailcallhq/core-windows-x86_64-msvc@0.14.14: wanted {"os":"windows-msvc","arch":"x86_64"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    windows-msvc
npm ERR! notsup Valid Arch:  x86_64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-11-10T03_32_25_782Z-debug-0.log

Failed to install optional dependency: @tailcallhq/core-linux-aarch64-musl npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @tailcallhq/core-linux-aarch64-musl@0.14.14: wanted {"os":"linux-musl","arch":"aarch64"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    linux-musl
npm ERR! notsup Valid Arch:  aarch64
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-11-10T03_32_25_495Z-debug-0.log

Failed to install optional dependency: @tailcallhq/core-linux-i686-gnu npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @tailcallhq/core-linux-i686-gnu@0.14.14: wanted {"os":"linux-gnu","arch":"i686"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    linux-gnu
npm ERR! notsup Valid Arch:  i686
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-11-10T03_32_25_426Z-debug-0.log
```

**Comment by jkcs** [comment]
This issue originates from the package '@tailcallhq/core-linux-*/package.json' .
 I believe its `os` field should be `["linux"]` instead of `["linux-musl"]`.

**Comment by amitksingh1490** [comment]
fixed in #607

**Comment by sc231997** [comment]
@amitksingh1490 I am still facing the issue. Sharing the logs below:
```
Failed to install optional dependency: @tailcallhq/core-linux-x64 npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tailcallhq%2fcore-linux-x64 - Not found
npm ERR! 404 
npm ERR! 404  '@tailcallhq/core-linux-x64@v0.15.1' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2023-11-18T04_27_45_530Z-debug-0.log
```
Using `@tailcallhq/tailcall` version : `0.15.1`

**Comment by sc231997** [comment]
@amitksingh1490 can we reopen the issue as its still occurring

**Comment by amitksingh1490** [comment]
@sc231997 we are using this on linux, x64.

could you please add the details and steps to reproduce.

**Comment by sc231997** [comment]
To reproduce just open this https://stackblitz.com/edit/tailcall-playground?file=index.js

**Comment by meskill** [comment]
I confirm problem with some version of linux due to the fact that libc is not defined in some environments and therefore tailcall's postinstall script fails with the attempt to download non-existing package (without libc postfix). In case if we can't resolve the libc version I think we should use musl anyway as the compilation produces statically linked binary in that case i.e. available for any linux platform. 

But, this won't solve the issue with stackblitz since is not an actual linux environment, but a webcontainer that implements some of the features of the OS. To be able to run tailcall on stackblitz in current state we'd require to build wasm binaries as prisma cli [does](https://github.com/prisma/prisma/issues/8626)

**Comment by sc231997** [comment]
As part of this issue just want installation of tailcall to happen on linux with x64 arch.

Running the tailcall on stackblitz is not actually in the scope as @meskill pointed out it will require wasm for this

**Comment by meskill** [comment]
> As part of this issue just want installation of tailcall to happen on linux with x64 arch.
> 
> Running the tailcall on stackblitz is not actually in the scope as @meskill pointed out it will require wasm for this

Are you saying you have the similar problem as on stackblitz on your local system as well? Could you point out the distro you are using then? We definitely do have builds for linux-x64, but they're made for different libc
